#========================== Filter Signatures
# Load drug_list
drug_list <- t(read.table("./data/predicted_drug_list.csv",sep = ",", stringsAsFactors = FALSE,quote = "", fill = TRUE, na.strings = c("NA", "")))

# Add information of cell lines 
drug_info_MCF7  <- data.frame(drug_name = as.data.frame(drug_list)$V1,cell_id = rep(paste0("MCF7"),nrow(drug_list)))
drug_info_PC3  <- data.frame(drug_name = as.data.frame(drug_list)$V1,cell_id = rep(paste0("PC3"),nrow(drug_list)))
drug_info <- rbind(drug_info_MCF7,drug_info_PC3)

# Load l1000_gene_list
gene_list <- as.data.frame(t(read.table("./data/l1000_gene_list.csv",sep = ",",quote = "",fill = TRUE,comment.char = "")))
gene_name <- gene_list$V1

# Load the predicted gene-expression matrices for the MCF-7 and PC-3 cell lines that were generated by DeepCE
predicted_mcf7 <- data.frame(t(read.table("./data/predicted_mcf7.csv",sep = ",")))
predicted_pc3 <- data.frame(t(read.table("./data/predicted_pc3.csv",sep = ",")))
drug_sig <- cbind(predicted_mcf7,predicted_pc3)
rownames(drug_sig) <- gene_name
colnames(drug_sig) <- rownames(drug_info)

